#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-awaitility
Version  : 3.1.6
Release  : 1
URL      : https://github.com/awaitility/awaitility/archive/awaitility-3.1.6.tar.gz
Source0  : https://github.com/awaitility/awaitility/archive/awaitility-3.1.6.tar.gz
Source1  : https://repo1.maven.org/maven2/org/awaitility/awaitility-parent/3.1.6/awaitility-parent-3.1.6.pom
Source2  : https://repo1.maven.org/maven2/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.jar
Source3  : https://repo1.maven.org/maven2/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-awaitility-data = %{version}-%{release}
Requires: mvn-awaitility-license = %{version}-%{release}

%description
![Awaitility](resources/Awaitility_logo_red_small.png)
[![Build Status](https://travis-ci.org/awaitility/awaitility.svg)](https://travis-ci.org/awaitility/awaitility)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/org.awaitility/awaitility/badge.svg)](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A"org.awaitility"%20AND%20a%3A"awaitility")
[![Javadoc](https://javadoc-badge.appspot.com/org.awaitility/awaitility.svg)](http://www.javadoc.io/doc/org.awaitility/awaitility)

%package data
Summary: data components for the mvn-awaitility package.
Group: Data

%description data
data components for the mvn-awaitility package.


%package license
Summary: license components for the mvn-awaitility package.
Group: Default

%description license
license components for the mvn-awaitility package.


%prep
%setup -q -n awaitility-awaitility-3.1.6

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-awaitility
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-awaitility/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility-parent/3.1.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility-parent/3.1.6/awaitility-parent-3.1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/awaitility/awaitility-parent/3.1.6/awaitility-parent-3.1.6.pom
/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.jar
/usr/share/java/.m2/repository/org/awaitility/awaitility/3.1.6/awaitility-3.1.6.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-awaitility/LICENSE
